# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\甲骨字检索程序-召回率82%\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 590)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(793, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(13, 522, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(3)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(3)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.tableWidget = QtWidgets.QTableWidget(self.page)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_12.addWidget(self.tableWidget)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 1000)
        self.horizontalLayout_12.setStretch(2, 1)
        self.verticalLayout_18.addLayout(self.horizontalLayout_12)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem5)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.top2 = QtWidgets.QLabel(self.page)
        self.top2.setMinimumSize(QtCore.QSize(150, 30))
        self.top2.setMaximumSize(QtCore.QSize(150, 30))
        self.top2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.top2.setText("")
        self.top2.setAlignment(QtCore.Qt.AlignCenter)
        self.top2.setObjectName("top2")
        self.horizontalLayout_13.addWidget(self.top2)
        self.top1 = QtWidgets.QLabel(self.page)
        self.top1.setMinimumSize(QtCore.QSize(150, 30))
        self.top1.setMaximumSize(QtCore.QSize(150, 30))
        self.top1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.top1.setText("")
        self.top1.setAlignment(QtCore.Qt.AlignCenter)
        self.top1.setObjectName("top1")
        self.horizontalLayout_13.addWidget(self.top1)
        self.top3 = QtWidgets.QLabel(self.page)
        self.top3.setMinimumSize(QtCore.QSize(150, 30))
        self.top3.setMaximumSize(QtCore.QSize(150, 30))
        self.top3.setStyleSheet("text-align:center")
        self.top3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.top3.setText("")
        self.top3.setAlignment(QtCore.Qt.AlignCenter)
        self.top3.setObjectName("top3")
        self.horizontalLayout_13.addWidget(self.top3)
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setEnabled(False)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_13.addWidget(self.pushButton)
        self.spinBox = QtWidgets.QSpinBox(self.page)
        self.spinBox.setMinimumSize(QtCore.QSize(100, 35))
        self.spinBox.setMaximumSize(QtCore.QSize(100, 35))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(10000)
        self.spinBox.setProperty("value", 200)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_13.addWidget(self.spinBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.horizontalLayout_13.setStretch(1, 150)
        self.horizontalLayout_13.setStretch(2, 150)
        self.horizontalLayout_13.setStretch(3, 150)
        self.horizontalLayout_13.setStretch(4, 150)
        self.horizontalLayout_13.setStretch(5, 100)
        self.verticalLayout_18.addLayout(self.horizontalLayout_13)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem8)
        self.verticalLayout_18.setStretch(0, 1)
        self.verticalLayout_18.setStretch(1, 500)
        self.verticalLayout_18.setStretch(2, 1)
        self.verticalLayout_18.setStretch(3, 30)
        self.verticalLayout_18.setStretch(4, 1)
        self.horizontalLayout_10.addLayout(self.verticalLayout_18)
        spacerItem9 = QtWidgets.QSpacerItem(13, 522, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(3)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        spacerItem10 = QtWidgets.QSpacerItem(99, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem10)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.left1 = QtWidgets.QPushButton(self.page)
        self.left1.setMinimumSize(QtCore.QSize(50, 35))
        self.left1.setMaximumSize(QtCore.QSize(35, 35))
        self.left1.setSizeIncrement(QtCore.QSize(35, 35))
        self.left1.setBaseSize(QtCore.QSize(35, 35))
        self.left1.setObjectName("left1")
        self.horizontalLayout_16.addWidget(self.left1)
        self.right1 = QtWidgets.QPushButton(self.page)
        self.right1.setMinimumSize(QtCore.QSize(50, 35))
        self.right1.setMaximumSize(QtCore.QSize(35, 35))
        self.right1.setSizeIncrement(QtCore.QSize(35, 35))
        self.right1.setBaseSize(QtCore.QSize(35, 35))
        self.right1.setObjectName("right1")
        self.horizontalLayout_16.addWidget(self.right1)
        self.verticalLayout_19.addLayout(self.horizontalLayout_16)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(3)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.image1 = QtWidgets.QLabel(self.page)
        self.image1.setMinimumSize(QtCore.QSize(100, 100))
        self.image1.setMaximumSize(QtCore.QSize(100, 100))
        self.image1.setFrameShape(QtWidgets.QFrame.Panel)
        self.image1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image1.setObjectName("image1")
        self.verticalLayout_20.addWidget(self.image1)
        self.image2 = QtWidgets.QLabel(self.page)
        self.image2.setMinimumSize(QtCore.QSize(100, 100))
        self.image2.setMaximumSize(QtCore.QSize(100, 100))
        self.image2.setFrameShape(QtWidgets.QFrame.Panel)
        self.image2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image2.setObjectName("image2")
        self.verticalLayout_20.addWidget(self.image2)
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setSpacing(3)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.open_image = QtWidgets.QPushButton(self.page)
        self.open_image.setMinimumSize(QtCore.QSize(100, 35))
        self.open_image.setMaximumSize(QtCore.QSize(100, 35))
        self.open_image.setSizeIncrement(QtCore.QSize(100, 35))
        self.open_image.setBaseSize(QtCore.QSize(100, 35))
        self.open_image.setObjectName("open_image")
        self.verticalLayout_21.addWidget(self.open_image)
        self.process_image = QtWidgets.QPushButton(self.page)
        self.process_image.setMinimumSize(QtCore.QSize(100, 35))
        self.process_image.setMaximumSize(QtCore.QSize(100, 35))
        self.process_image.setSizeIncrement(QtCore.QSize(100, 35))
        self.process_image.setBaseSize(QtCore.QSize(100, 35))
        self.process_image.setObjectName("process_image")
        self.verticalLayout_21.addWidget(self.process_image)
        self.search_image = QtWidgets.QPushButton(self.page)
        self.search_image.setMinimumSize(QtCore.QSize(100, 35))
        self.search_image.setMaximumSize(QtCore.QSize(100, 35))
        self.search_image.setSizeIncrement(QtCore.QSize(100, 35))
        self.search_image.setBaseSize(QtCore.QSize(100, 35))
        self.search_image.setObjectName("search_image")
        self.verticalLayout_21.addWidget(self.search_image)
        self.verticalLayout_19.addLayout(self.verticalLayout_21)
        spacerItem11 = QtWidgets.QSpacerItem(99, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem11)
        self.verticalLayout_19.setStretch(0, 1)
        self.verticalLayout_19.setStretch(1, 35)
        self.verticalLayout_19.setStretch(2, 200)
        self.verticalLayout_19.setStretch(4, 1)
        self.horizontalLayout_10.addLayout(self.verticalLayout_19)
        spacerItem12 = QtWidgets.QSpacerItem(13, 522, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 100)
        self.horizontalLayout_10.setStretch(2, 1)
        self.horizontalLayout_10.setStretch(3, 20)
        self.horizontalLayout_10.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem13 = QtWidgets.QSpacerItem(793, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 100)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout_17.addLayout(self.verticalLayout)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem14)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem16)
        self.image_roi = QtWidgets.QLabel(self.page_2)
        self.image_roi.setMinimumSize(QtCore.QSize(0, 0))
        self.image_roi.setSizeIncrement(QtCore.QSize(0, 0))
        self.image_roi.setBaseSize(QtCore.QSize(0, 0))
        self.image_roi.setFrameShape(QtWidgets.QFrame.Panel)
        self.image_roi.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_roi.setObjectName("image_roi")
        self.verticalLayout_6.addWidget(self.image_roi)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem17)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 100)
        self.verticalLayout_6.setStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem18)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem19)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.left2 = QtWidgets.QPushButton(self.page_2)
        self.left2.setMinimumSize(QtCore.QSize(50, 35))
        self.left2.setMaximumSize(QtCore.QSize(50, 35))
        self.left2.setSizeIncrement(QtCore.QSize(35, 35))
        self.left2.setBaseSize(QtCore.QSize(35, 35))
        self.left2.setObjectName("left2")
        self.horizontalLayout_14.addWidget(self.left2)
        self.right2 = QtWidgets.QPushButton(self.page_2)
        self.right2.setMinimumSize(QtCore.QSize(50, 35))
        self.right2.setMaximumSize(QtCore.QSize(50, 35))
        self.right2.setSizeIncrement(QtCore.QSize(35, 35))
        self.right2.setBaseSize(QtCore.QSize(35, 35))
        self.right2.setObjectName("right2")
        self.horizontalLayout_14.addWidget(self.right2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.reset = QtWidgets.QPushButton(self.page_2)
        self.reset.setMinimumSize(QtCore.QSize(100, 35))
        self.reset.setMaximumSize(QtCore.QSize(100, 35))
        self.reset.setSizeIncrement(QtCore.QSize(100, 35))
        self.reset.setBaseSize(QtCore.QSize(100, 35))
        self.reset.setObjectName("reset")
        self.verticalLayout_10.addWidget(self.reset)
        self.roi_rect = QtWidgets.QPushButton(self.page_2)
        self.roi_rect.setMinimumSize(QtCore.QSize(100, 35))
        self.roi_rect.setMaximumSize(QtCore.QSize(100, 35))
        self.roi_rect.setSizeIncrement(QtCore.QSize(100, 35))
        self.roi_rect.setBaseSize(QtCore.QSize(100, 35))
        self.roi_rect.setObjectName("roi_rect")
        self.verticalLayout_10.addWidget(self.roi_rect)
        self.roi_dot = QtWidgets.QPushButton(self.page_2)
        self.roi_dot.setMinimumSize(QtCore.QSize(100, 35))
        self.roi_dot.setMaximumSize(QtCore.QSize(100, 35))
        self.roi_dot.setSizeIncrement(QtCore.QSize(100, 35))
        self.roi_dot.setBaseSize(QtCore.QSize(100, 35))
        self.roi_dot.setObjectName("roi_dot")
        self.verticalLayout_10.addWidget(self.roi_dot)
        self.save = QtWidgets.QPushButton(self.page_2)
        self.save.setMinimumSize(QtCore.QSize(100, 35))
        self.save.setMaximumSize(QtCore.QSize(100, 35))
        self.save.setSizeIncrement(QtCore.QSize(100, 35))
        self.save.setBaseSize(QtCore.QSize(100, 35))
        self.save.setObjectName("save")
        self.verticalLayout_10.addWidget(self.save)
        self.verticalLayout_5.addLayout(self.verticalLayout_10)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem20)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem21)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 100)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 20)
        self.horizontalLayout_3.setStretch(4, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem22)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 100)
        self.verticalLayout_7.setStretch(2, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem23)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem24)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem25)
        self.tableWidget2 = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget2.setMinimumSize(QtCore.QSize(100, 100))
        self.tableWidget2.setObjectName("tableWidget2")
        self.tableWidget2.setColumnCount(0)
        self.tableWidget2.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.tableWidget2)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem26)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 100)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem27)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 100)
        self.verticalLayout_12.setStretch(2, 1)
        self.horizontalLayout_11.addLayout(self.verticalLayout_12)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem28)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem29)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.left3 = QtWidgets.QPushButton(self.page_3)
        self.left3.setMinimumSize(QtCore.QSize(50, 35))
        self.left3.setMaximumSize(QtCore.QSize(35, 35))
        self.left3.setSizeIncrement(QtCore.QSize(35, 35))
        self.left3.setBaseSize(QtCore.QSize(35, 35))
        self.left3.setObjectName("left3")
        self.horizontalLayout_15.addWidget(self.left3)
        self.right3 = QtWidgets.QPushButton(self.page_3)
        self.right3.setMinimumSize(QtCore.QSize(50, 35))
        self.right3.setMaximumSize(QtCore.QSize(35, 35))
        self.right3.setSizeIncrement(QtCore.QSize(35, 35))
        self.right3.setBaseSize(QtCore.QSize(35, 35))
        self.right3.setObjectName("right3")
        self.horizontalLayout_15.addWidget(self.right3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.image_selected = QtWidgets.QLabel(self.page_3)
        self.image_selected.setMinimumSize(QtCore.QSize(100, 100))
        self.image_selected.setMaximumSize(QtCore.QSize(100, 100))
        self.image_selected.setFrameShape(QtWidgets.QFrame.Panel)
        self.image_selected.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_selected.setObjectName("image_selected")
        self.verticalLayout_11.addWidget(self.image_selected)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.jgz = QtWidgets.QLabel(self.page_3)
        self.jgz.setMinimumSize(QtCore.QSize(100, 30))
        self.jgz.setMaximumSize(QtCore.QSize(100, 30))
        self.jgz.setFrameShape(QtWidgets.QFrame.Panel)
        self.jgz.setFrameShadow(QtWidgets.QFrame.Raised)
        self.jgz.setObjectName("jgz")
        self.verticalLayout_8.addWidget(self.jgz)
        self.ftz = QtWidgets.QLabel(self.page_3)
        self.ftz.setMinimumSize(QtCore.QSize(100, 30))
        self.ftz.setMaximumSize(QtCore.QSize(100, 30))
        self.ftz.setFrameShape(QtWidgets.QFrame.Panel)
        self.ftz.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ftz.setObjectName("ftz")
        self.verticalLayout_8.addWidget(self.ftz)
        self.ldz = QtWidgets.QLabel(self.page_3)
        self.ldz.setMinimumSize(QtCore.QSize(100, 30))
        self.ldz.setMaximumSize(QtCore.QSize(100, 30))
        self.ldz.setFrameShape(QtWidgets.QFrame.Panel)
        self.ldz.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ldz.setObjectName("ldz")
        self.verticalLayout_8.addWidget(self.ldz)
        self.jtz = QtWidgets.QLabel(self.page_3)
        self.jtz.setMinimumSize(QtCore.QSize(100, 30))
        self.jtz.setMaximumSize(QtCore.QSize(100, 30))
        self.jtz.setFrameShape(QtWidgets.QFrame.Panel)
        self.jtz.setFrameShadow(QtWidgets.QFrame.Raised)
        self.jtz.setObjectName("jtz")
        self.verticalLayout_8.addWidget(self.jtz)
        self.num_same = QtWidgets.QLabel(self.page_3)
        self.num_same.setMinimumSize(QtCore.QSize(100, 30))
        self.num_same.setMaximumSize(QtCore.QSize(100, 30))
        self.num_same.setFrameShape(QtWidgets.QFrame.Panel)
        self.num_same.setFrameShadow(QtWidgets.QFrame.Raised)
        self.num_same.setObjectName("num_same")
        self.verticalLayout_8.addWidget(self.num_same)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem30)
        self.verticalLayout_11.setStretch(0, 1)
        self.verticalLayout_11.setStretch(1, 35)
        self.verticalLayout_11.setStretch(2, 100)
        self.verticalLayout_11.setStretch(3, 175)
        self.verticalLayout_11.setStretch(4, 1)
        self.horizontalLayout_11.addLayout(self.verticalLayout_11)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem31)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 100)
        self.horizontalLayout_11.setStretch(2, 1)
        self.horizontalLayout_11.setStretch(3, 20)
        self.horizontalLayout_11.setStretch(4, 1)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem32)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem33)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem34)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem35)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem36)
        self.rubbing = QtWidgets.QLabel(self.page_4)
        self.rubbing.setFrameShape(QtWidgets.QFrame.Panel)
        self.rubbing.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rubbing.setObjectName("rubbing")
        self.horizontalLayout_7.addWidget(self.rubbing)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem37)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1000)
        self.horizontalLayout_7.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem38 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem38)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1000)
        self.verticalLayout_4.setStretch(2, 1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem39)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem40)
        self.textEdit = QtWidgets.QTextEdit(self.page_4)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 160))
        self.textEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        spacerItem41 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem41)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem42)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.left4 = QtWidgets.QPushButton(self.page_4)
        self.left4.setMinimumSize(QtCore.QSize(50, 35))
        self.left4.setMaximumSize(QtCore.QSize(35, 35))
        self.left4.setSizeIncrement(QtCore.QSize(35, 35))
        self.left4.setBaseSize(QtCore.QSize(35, 35))
        self.left4.setObjectName("left4")
        self.horizontalLayout_18.addWidget(self.left4)
        self.right4 = QtWidgets.QPushButton(self.page_4)
        self.right4.setMinimumSize(QtCore.QSize(50, 35))
        self.right4.setMaximumSize(QtCore.QSize(35, 35))
        self.right4.setSizeIncrement(QtCore.QSize(35, 35))
        self.right4.setBaseSize(QtCore.QSize(35, 35))
        self.right4.setObjectName("right4")
        self.horizontalLayout_18.addWidget(self.right4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_18)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem43)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem44)
        self.textEdit2 = QtWidgets.QTextEdit(self.page_4)
        self.textEdit2.setMinimumSize(QtCore.QSize(0, 160))
        self.textEdit2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.textEdit2.setObjectName("textEdit2")
        self.verticalLayout_3.addWidget(self.textEdit2)
        spacerItem45 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem45)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem46)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 500)
        self.horizontalLayout_8.setStretch(2, 1)
        self.horizontalLayout_8.setStretch(3, 200)
        self.horizontalLayout_8.setStretch(4, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        spacerItem47 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem47)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 1000)
        self.verticalLayout_9.setStretch(2, 1)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem48)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1000)
        self.horizontalLayout_9.setStretch(2, 1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.stackedWidget.addWidget(self.page_4)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 1000)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Retrieval System"))
        self.pushButton.setText(_translate("MainWindow", "搜索结果显示个数：200"))
        self.left1.setText(_translate("MainWindow", "<-"))
        self.right1.setText(_translate("MainWindow", "->"))
        self.image1.setText(_translate("MainWindow", "原始图像"))
        self.image2.setText(_translate("MainWindow", "待检索图像"))
        self.open_image.setText(_translate("MainWindow", "选择图像"))
        self.process_image.setText(_translate("MainWindow", "调整图像"))
        self.search_image.setText(_translate("MainWindow", "检索"))
        self.image_roi.setText(_translate("MainWindow", "框选"))
        self.left2.setText(_translate("MainWindow", "<-"))
        self.right2.setText(_translate("MainWindow", "->"))
        self.reset.setText(_translate("MainWindow", "重置"))
        self.roi_rect.setText(_translate("MainWindow", "矩形框选"))
        self.roi_dot.setText(_translate("MainWindow", "瞄点框选"))
        self.save.setText(_translate("MainWindow", "保存"))
        self.left3.setText(_translate("MainWindow", "<-"))
        self.right3.setText(_translate("MainWindow", "->"))
        self.image_selected.setText(_translate("MainWindow", "搜索结果图像"))
        self.jgz.setText(_translate("MainWindow", "甲骨字"))
        self.ftz.setText(_translate("MainWindow", "繁体字"))
        self.ldz.setText(_translate("MainWindow", "隶定字"))
        self.jtz.setText(_translate("MainWindow", "简体字"))
        self.num_same.setText(_translate("MainWindow", "异形字个数"))
        self.rubbing.setText(_translate("MainWindow", "rubbing"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.left4.setText(_translate("MainWindow", "<-"))
        self.right4.setText(_translate("MainWindow", "->"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

